[build]
  command = "yarn build && bundle exec rails assets:precompile"
  publish = "public"

[context.production]
  environment = { NODE_VERSION = "16.x", RUBY_VERSION = "3.2.0" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 