databases:
  - name: budget_manager
    databaseName: budget_manager_ui18
    user: budget_manager_ui18_user

services:
  - type: web
    name: budget_manage
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_manager
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false